// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config_writer.proto

package config_writer

import (
	context "context"
	fmt "fmt"
	tars "github.com/TarsCloud/TarsGo/tars"
	model "github.com/TarsCloud/TarsGo/tars/model"
	requestf "github.com/TarsCloud/TarsGo/tars/protocol/res/requestf"
	current "github.com/TarsCloud/TarsGo/tars/util/current"
	tools "github.com/TarsCloud/TarsGo/tars/util/tools"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type STATUS_TYPE int32

const (
	STATUS_TYPE_ONLINE  STATUS_TYPE = 0
	STATUS_TYPE_OFFLINE STATUS_TYPE = 1
)

var STATUS_TYPE_name = map[int32]string{
	0: "ONLINE",
	1: "OFFLINE",
}

var STATUS_TYPE_value = map[string]int32{
	"ONLINE":  0,
	"OFFLINE": 1,
}

func (x STATUS_TYPE) String() string {
	return proto.EnumName(STATUS_TYPE_name, int32(x))
}

func (STATUS_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b56d2b8152742171, []int{0}
}

type ITEM_TYPE int32

const (
	ITEM_TYPE_TEXT ITEM_TYPE = 0
	ITEM_TYPE_JSON ITEM_TYPE = 1
	ITEM_TYPE_YAML ITEM_TYPE = 2
)

var ITEM_TYPE_name = map[int32]string{
	0: "TEXT",
	1: "JSON",
	2: "YAML",
}

var ITEM_TYPE_value = map[string]int32{
	"TEXT": 0,
	"JSON": 1,
	"YAML": 2,
}

func (x ITEM_TYPE) String() string {
	return proto.EnumName(ITEM_TYPE_name, int32(x))
}

func (ITEM_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b56d2b8152742171, []int{1}
}

type Config struct {
	ID                   uint64       `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Secret               string       `protobuf:"bytes,2,opt,name=Secret,proto3" json:"Secret,omitempty"`
	Status               STATUS_TYPE  `protobuf:"varint,3,opt,name=Status,proto3,enum=tars_vcms.config.config_writer.STATUS_TYPE" json:"Status,omitempty"`
	Comment              string       `protobuf:"bytes,4,opt,name=Comment,proto3" json:"Comment,omitempty"`
	Env                  []*ConfigEnv `protobuf:"bytes,5,rep,name=Env,proto3" json:"Env,omitempty"`
	CreatedAt            uint64       `protobuf:"varint,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_b56d2b8152742171, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Config) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *Config) GetStatus() STATUS_TYPE {
	if m != nil {
		return m.Status
	}
	return STATUS_TYPE_ONLINE
}

func (m *Config) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *Config) GetEnv() []*ConfigEnv {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *Config) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type ConfigEnv struct {
	ID                   uint64        `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ConfigID             uint64        `protobuf:"varint,2,opt,name=ConfigID,proto3" json:"ConfigID,omitempty"`
	Item                 []*ConfigItem `protobuf:"bytes,3,rep,name=item,proto3" json:"item,omitempty"`
	Name                 string        `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	CreatedAt            uint64        `protobuf:"varint,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ConfigEnv) Reset()         { *m = ConfigEnv{} }
func (m *ConfigEnv) String() string { return proto.CompactTextString(m) }
func (*ConfigEnv) ProtoMessage()    {}
func (*ConfigEnv) Descriptor() ([]byte, []int) {
	return fileDescriptor_b56d2b8152742171, []int{1}
}

func (m *ConfigEnv) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigEnv.Unmarshal(m, b)
}
func (m *ConfigEnv) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigEnv.Marshal(b, m, deterministic)
}
func (m *ConfigEnv) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigEnv.Merge(m, src)
}
func (m *ConfigEnv) XXX_Size() int {
	return xxx_messageInfo_ConfigEnv.Size(m)
}
func (m *ConfigEnv) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigEnv.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigEnv proto.InternalMessageInfo

func (m *ConfigEnv) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ConfigEnv) GetConfigID() uint64 {
	if m != nil {
		return m.ConfigID
	}
	return 0
}

func (m *ConfigEnv) GetItem() []*ConfigItem {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *ConfigEnv) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ConfigEnv) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type ConfigItem struct {
	ID                   uint64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ConfigEnvID          uint64    `protobuf:"varint,2,opt,name=ConfigEnvID,proto3" json:"ConfigEnvID,omitempty"`
	Version              uint64    `protobuf:"varint,3,opt,name=Version,proto3" json:"Version,omitempty"`
	Name                 string    `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	Type                 ITEM_TYPE `protobuf:"varint,5,opt,name=Type,proto3,enum=tars_vcms.config.config_writer.ITEM_TYPE" json:"Type,omitempty"`
	Content              string    `protobuf:"bytes,6,opt,name=Content,proto3" json:"Content,omitempty"`
	Comment              string    `protobuf:"bytes,7,opt,name=Comment,proto3" json:"Comment,omitempty"`
	CreatedAt            uint64    `protobuf:"varint,8,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ConfigItem) Reset()         { *m = ConfigItem{} }
func (m *ConfigItem) String() string { return proto.CompactTextString(m) }
func (*ConfigItem) ProtoMessage()    {}
func (*ConfigItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_b56d2b8152742171, []int{2}
}

func (m *ConfigItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigItem.Unmarshal(m, b)
}
func (m *ConfigItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigItem.Marshal(b, m, deterministic)
}
func (m *ConfigItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigItem.Merge(m, src)
}
func (m *ConfigItem) XXX_Size() int {
	return xxx_messageInfo_ConfigItem.Size(m)
}
func (m *ConfigItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigItem.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigItem proto.InternalMessageInfo

func (m *ConfigItem) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ConfigItem) GetConfigEnvID() uint64 {
	if m != nil {
		return m.ConfigEnvID
	}
	return 0
}

func (m *ConfigItem) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ConfigItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ConfigItem) GetType() ITEM_TYPE {
	if m != nil {
		return m.Type
	}
	return ITEM_TYPE_TEXT
}

func (m *ConfigItem) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ConfigItem) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *ConfigItem) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type InsertConfigRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertConfigRequest) Reset()         { *m = InsertConfigRequest{} }
func (m *InsertConfigRequest) String() string { return proto.CompactTextString(m) }
func (*InsertConfigRequest) ProtoMessage()    {}
func (*InsertConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b56d2b8152742171, []int{3}
}

func (m *InsertConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertConfigRequest.Unmarshal(m, b)
}
func (m *InsertConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertConfigRequest.Marshal(b, m, deterministic)
}
func (m *InsertConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertConfigRequest.Merge(m, src)
}
func (m *InsertConfigRequest) XXX_Size() int {
	return xxx_messageInfo_InsertConfigRequest.Size(m)
}
func (m *InsertConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InsertConfigRequest proto.InternalMessageInfo

func (m *InsertConfigRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type InsertConfigReply struct {
	Config               *Config  `protobuf:"bytes,1,opt,name=Config,proto3" json:"Config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertConfigReply) Reset()         { *m = InsertConfigReply{} }
func (m *InsertConfigReply) String() string { return proto.CompactTextString(m) }
func (*InsertConfigReply) ProtoMessage()    {}
func (*InsertConfigReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b56d2b8152742171, []int{4}
}

func (m *InsertConfigReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertConfigReply.Unmarshal(m, b)
}
func (m *InsertConfigReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertConfigReply.Marshal(b, m, deterministic)
}
func (m *InsertConfigReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertConfigReply.Merge(m, src)
}
func (m *InsertConfigReply) XXX_Size() int {
	return xxx_messageInfo_InsertConfigReply.Size(m)
}
func (m *InsertConfigReply) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertConfigReply.DiscardUnknown(m)
}

var xxx_messageInfo_InsertConfigReply proto.InternalMessageInfo

func (m *InsertConfigReply) GetConfig() *Config {
	if m != nil {
		return m.Config
	}
	return nil
}

type GetConfigsRequest struct {
	Cid                  []uint64 `protobuf:"varint,1,rep,packed,name=Cid,proto3" json:"Cid,omitempty"`
	Name                 []uint64 `protobuf:"varint,2,rep,packed,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigsRequest) Reset()         { *m = GetConfigsRequest{} }
func (m *GetConfigsRequest) String() string { return proto.CompactTextString(m) }
func (*GetConfigsRequest) ProtoMessage()    {}
func (*GetConfigsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b56d2b8152742171, []int{5}
}

func (m *GetConfigsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigsRequest.Unmarshal(m, b)
}
func (m *GetConfigsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigsRequest.Marshal(b, m, deterministic)
}
func (m *GetConfigsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigsRequest.Merge(m, src)
}
func (m *GetConfigsRequest) XXX_Size() int {
	return xxx_messageInfo_GetConfigsRequest.Size(m)
}
func (m *GetConfigsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigsRequest proto.InternalMessageInfo

func (m *GetConfigsRequest) GetCid() []uint64 {
	if m != nil {
		return m.Cid
	}
	return nil
}

func (m *GetConfigsRequest) GetName() []uint64 {
	if m != nil {
		return m.Name
	}
	return nil
}

type GetConfigsReply struct {
	Config               []*Config `protobuf:"bytes,1,rep,name=Config,proto3" json:"Config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetConfigsReply) Reset()         { *m = GetConfigsReply{} }
func (m *GetConfigsReply) String() string { return proto.CompactTextString(m) }
func (*GetConfigsReply) ProtoMessage()    {}
func (*GetConfigsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b56d2b8152742171, []int{6}
}

func (m *GetConfigsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigsReply.Unmarshal(m, b)
}
func (m *GetConfigsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigsReply.Marshal(b, m, deterministic)
}
func (m *GetConfigsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigsReply.Merge(m, src)
}
func (m *GetConfigsReply) XXX_Size() int {
	return xxx_messageInfo_GetConfigsReply.Size(m)
}
func (m *GetConfigsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigsReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigsReply proto.InternalMessageInfo

func (m *GetConfigsReply) GetConfig() []*Config {
	if m != nil {
		return m.Config
	}
	return nil
}

type UpdateConfigRequest struct {
	Config               *Config  `protobuf:"bytes,1,opt,name=Config,proto3" json:"Config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateConfigRequest) Reset()         { *m = UpdateConfigRequest{} }
func (m *UpdateConfigRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateConfigRequest) ProtoMessage()    {}
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b56d2b8152742171, []int{7}
}

func (m *UpdateConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateConfigRequest.Unmarshal(m, b)
}
func (m *UpdateConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateConfigRequest.Marshal(b, m, deterministic)
}
func (m *UpdateConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateConfigRequest.Merge(m, src)
}
func (m *UpdateConfigRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateConfigRequest.Size(m)
}
func (m *UpdateConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateConfigRequest proto.InternalMessageInfo

func (m *UpdateConfigRequest) GetConfig() *Config {
	if m != nil {
		return m.Config
	}
	return nil
}

type UpdateConfigReply struct {
	Config               *Config  `protobuf:"bytes,1,opt,name=Config,proto3" json:"Config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateConfigReply) Reset()         { *m = UpdateConfigReply{} }
func (m *UpdateConfigReply) String() string { return proto.CompactTextString(m) }
func (*UpdateConfigReply) ProtoMessage()    {}
func (*UpdateConfigReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b56d2b8152742171, []int{8}
}

func (m *UpdateConfigReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateConfigReply.Unmarshal(m, b)
}
func (m *UpdateConfigReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateConfigReply.Marshal(b, m, deterministic)
}
func (m *UpdateConfigReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateConfigReply.Merge(m, src)
}
func (m *UpdateConfigReply) XXX_Size() int {
	return xxx_messageInfo_UpdateConfigReply.Size(m)
}
func (m *UpdateConfigReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateConfigReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateConfigReply proto.InternalMessageInfo

func (m *UpdateConfigReply) GetConfig() *Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func init() {
	proto.RegisterEnum("tars_vcms.config.config_writer.STATUS_TYPE", STATUS_TYPE_name, STATUS_TYPE_value)
	proto.RegisterEnum("tars_vcms.config.config_writer.ITEM_TYPE", ITEM_TYPE_name, ITEM_TYPE_value)
	proto.RegisterType((*Config)(nil), "tars_vcms.config.config_writer.Config")
	proto.RegisterType((*ConfigEnv)(nil), "tars_vcms.config.config_writer.ConfigEnv")
	proto.RegisterType((*ConfigItem)(nil), "tars_vcms.config.config_writer.ConfigItem")
	proto.RegisterType((*InsertConfigRequest)(nil), "tars_vcms.config.config_writer.InsertConfigRequest")
	proto.RegisterType((*InsertConfigReply)(nil), "tars_vcms.config.config_writer.InsertConfigReply")
	proto.RegisterType((*GetConfigsRequest)(nil), "tars_vcms.config.config_writer.GetConfigsRequest")
	proto.RegisterType((*GetConfigsReply)(nil), "tars_vcms.config.config_writer.GetConfigsReply")
	proto.RegisterType((*UpdateConfigRequest)(nil), "tars_vcms.config.config_writer.UpdateConfigRequest")
	proto.RegisterType((*UpdateConfigReply)(nil), "tars_vcms.config.config_writer.UpdateConfigReply")
}

func init() { proto.RegisterFile("config_writer.proto", fileDescriptor_b56d2b8152742171) }

var fileDescriptor_b56d2b8152742171 = []byte{
	// 570 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x51, 0x8f, 0xd2, 0x4c,
	0x14, 0xdd, 0x69, 0xbb, 0x05, 0x2e, 0x7c, 0x2c, 0x0c, 0xc9, 0x97, 0x86, 0x18, 0xd3, 0xf0, 0xb0,
	0x01, 0x8c, 0x18, 0xd9, 0x27, 0x63, 0xdc, 0x04, 0xa1, 0x6b, 0x6a, 0x76, 0x41, 0xa7, 0x45, 0x5d,
	0x5f, 0x08, 0xc2, 0x68, 0x48, 0x6c, 0xc1, 0x76, 0x16, 0xb3, 0x3f, 0xc9, 0xbf, 0xe6, 0x93, 0x7f,
	0xc0, 0xc4, 0x74, 0xa6, 0x2d, 0x2d, 0xdd, 0xd8, 0x5d, 0xf5, 0x6d, 0xee, 0xed, 0x3d, 0xf7, 0x9e,
	0x73, 0xcf, 0x25, 0x40, 0x63, 0xb1, 0x76, 0x3f, 0xae, 0x3e, 0xcd, 0xbe, 0x7a, 0x2b, 0x46, 0xbd,
	0xde, 0xc6, 0x5b, 0xb3, 0x35, 0xbe, 0xcf, 0xe6, 0x9e, 0x3f, 0xdb, 0x2e, 0x1c, 0xbf, 0x27, 0x3e,
	0xf7, 0x52, 0x55, 0xad, 0xef, 0x08, 0xd4, 0x21, 0xcf, 0xe0, 0x2a, 0x48, 0xe6, 0x48, 0x43, 0x3a,
	0x6a, 0x2b, 0x44, 0x32, 0x47, 0xf8, 0x7f, 0x50, 0x2d, 0xba, 0xf0, 0x28, 0xd3, 0x24, 0x1d, 0xb5,
	0x4b, 0x24, 0x8c, 0xf0, 0x10, 0x54, 0x8b, 0xcd, 0xd9, 0x95, 0xaf, 0xc9, 0x3a, 0x6a, 0x57, 0xfb,
	0x0f, 0x7a, 0xbf, 0x9f, 0xd1, 0xb3, 0xec, 0x81, 0x3d, 0xb5, 0x66, 0xf6, 0xe5, 0x2b, 0x83, 0x84,
	0x50, 0xac, 0x41, 0x61, 0xb8, 0x76, 0x1c, 0xea, 0x32, 0x4d, 0xe1, 0xdd, 0xa3, 0x10, 0x3f, 0x05,
	0xd9, 0x70, 0xb7, 0xda, 0xa1, 0x2e, 0xb7, 0xcb, 0xfd, 0x4e, 0x5e, 0x6f, 0xc1, 0xdd, 0x70, 0xb7,
	0x24, 0x40, 0xe1, 0x7b, 0x50, 0x1a, 0x7a, 0x74, 0xce, 0xe8, 0x72, 0xc0, 0x34, 0x95, 0x4b, 0xd9,
	0x25, 0x5a, 0xdf, 0x10, 0x94, 0x62, 0x40, 0x46, 0x6f, 0x13, 0x8a, 0xe2, 0xa3, 0x39, 0xe2, 0x8a,
	0x15, 0x12, 0xc7, 0xf8, 0x14, 0x94, 0x15, 0xa3, 0x8e, 0x26, 0x73, 0x56, 0xdd, 0xdb, 0xb1, 0x32,
	0x19, 0x75, 0x08, 0xc7, 0x61, 0x0c, 0xca, 0x78, 0xee, 0xd0, 0x50, 0x2b, 0x7f, 0xa7, 0xb9, 0x1e,
	0xee, 0x73, 0xfd, 0x89, 0x00, 0x76, 0x6d, 0x32, 0x64, 0x75, 0x28, 0xc7, 0x4a, 0x62, 0xbe, 0xc9,
	0x54, 0xb0, 0xe1, 0x37, 0xd4, 0xf3, 0x57, 0x6b, 0x97, 0xfb, 0xa4, 0x90, 0x28, 0xbc, 0x91, 0xcc,
	0x33, 0x50, 0xec, 0xeb, 0x0d, 0xe5, 0x3c, 0xaa, 0xf9, 0x6b, 0x37, 0x6d, 0xe3, 0x42, 0x18, 0xca,
	0x61, 0xc2, 0x4e, 0x97, 0x05, 0x76, 0xaa, 0x91, 0x9d, 0x3c, 0x4c, 0x1a, 0x5d, 0x48, 0x1b, 0x9d,
	0xd2, 0x5f, 0xdc, 0xd7, 0xdf, 0x81, 0x86, 0xe9, 0xfa, 0xd4, 0x63, 0x42, 0x13, 0xa1, 0x5f, 0xae,
	0xa8, 0xcf, 0x62, 0xee, 0x68, 0xc7, 0xbd, 0x65, 0x41, 0x3d, 0x5d, 0xba, 0xf9, 0x7c, 0x8d, 0x4f,
	0xa3, 0xbb, 0xe6, 0xa5, 0xe5, 0xfe, 0xf1, 0xed, 0x3c, 0x23, 0x21, 0xaa, 0xf5, 0x04, 0xea, 0x2f,
	0x68, 0xd8, 0xd1, 0x8f, 0xa6, 0xd7, 0x40, 0x1e, 0xae, 0x96, 0x1a, 0xd2, 0xe5, 0xb6, 0x42, 0x82,
	0x67, 0xcc, 0x47, 0xe2, 0x29, 0xc1, 0xe7, 0x35, 0x1c, 0x25, 0xa1, 0xfb, 0x6c, 0xe4, 0x3f, 0x60,
	0x33, 0x85, 0xc6, 0x74, 0xb3, 0x9c, 0x33, 0x9a, 0xde, 0xc6, 0xdf, 0x8a, 0xb4, 0xa0, 0x9e, 0x6e,
	0xfb, 0x0f, 0x36, 0xd7, 0x3d, 0x86, 0x72, 0xe2, 0x17, 0x8f, 0x01, 0xd4, 0xc9, 0xf8, 0xdc, 0x1c,
	0x1b, 0xb5, 0x03, 0x5c, 0x86, 0xc2, 0xe4, 0xec, 0x8c, 0x07, 0xa8, 0xdb, 0x81, 0x52, 0x7c, 0x46,
	0xb8, 0x08, 0x8a, 0x6d, 0xbc, 0xb3, 0x6b, 0x07, 0xc1, 0xeb, 0xa5, 0x35, 0x19, 0xd7, 0x50, 0xf0,
	0xba, 0x1c, 0x5c, 0x9c, 0xd7, 0xa4, 0xfe, 0x0f, 0x09, 0x2a, 0xa2, 0xfb, 0x5b, 0x3e, 0x12, 0x6f,
	0xa1, 0x92, 0xb4, 0x1c, 0x9f, 0xe4, 0x1e, 0x6c, 0xf6, 0x96, 0x9a, 0x8f, 0xef, 0x06, 0x0a, 0x76,
	0xb3, 0x01, 0xd8, 0x59, 0x8b, 0x73, 0x1b, 0x64, 0x2e, 0xa8, 0xf9, 0xe8, 0x2e, 0x90, 0x60, 0xe2,
	0x16, 0x2a, 0x49, 0x8b, 0xf2, 0x95, 0xde, 0x70, 0x27, 0xf9, 0x4a, 0x33, 0x57, 0xf0, 0xfc, 0xe8,
	0xfd, 0x7f, 0xa2, 0xe4, 0xa1, 0x28, 0xf9, 0xa0, 0xf2, 0x3f, 0x94, 0x93, 0x5f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x45, 0x3f, 0x3e, 0xfa, 0x67, 0x06, 0x00, 0x00,
}

// This following code was generated by tarsrpc
// Gernerated from config_writer.proto
type ConfigWriter struct {
	s model.Servant
}

//SetServant is required by the servant interface.
func (obj *ConfigWriter) SetServant(s model.Servant) {
	obj.s = s
}

//AddServant is required by the servant interface
func (obj *ConfigWriter) AddServant(imp impConfigWriter, objStr string) {
	tars.AddServant(obj, imp, objStr)
}

////AddServant adds servant  for the service with context
func (obj *ConfigWriter) AddServantWithContext(imp impConfigWriterWithContext, objStr string) {
	tars.AddServantWithContext(obj, imp, objStr)
}

//TarsSetTimeout is required by the servant interface. t is the timeout in ms.
func (obj *ConfigWriter) TarsSetTimeout(t int) {
	obj.s.TarsSetTimeout(t)
}

//TarsSetProtocol is required by the servant interface. t is the protocol.
func (obj *ConfigWriter) TarsSetProtocol(p model.Protocol) {
	obj.s.TarsSetProtocol(p)
}

type impConfigWriter interface {
	InsertConfig(input InsertConfigRequest) (output InsertConfigReply, err error)
	GetConfigs(input GetConfigsRequest) (output GetConfigsReply, err error)
	UpdateConfig(input UpdateConfigRequest) (output UpdateConfigReply, err error)
}

type impConfigWriterWithContext interface {
	InsertConfig(ctx context.Context, input InsertConfigRequest) (output InsertConfigReply, err error)
	GetConfigs(ctx context.Context, input GetConfigsRequest) (output GetConfigsReply, err error)
	UpdateConfig(ctx context.Context, input UpdateConfigRequest) (output UpdateConfigReply, err error)
}

//Dispatch is used to call the user implement of the defined method.
func (obj *ConfigWriter) Dispatch(ctx context.Context, val interface{}, req *requestf.RequestPacket, resp *requestf.ResponsePacket, withContext bool) (err error) {
	input := tools.Int8ToByte(req.SBuffer)
	var output []byte
	funcName := req.SFuncName
	switch funcName {

	case "InsertConfig":
		inputDefine := InsertConfigRequest{}
		if err = proto.Unmarshal(input, &inputDefine); err != nil {
			return err
		}
		var res InsertConfigReply
		if withContext == false {
			imp := val.(impConfigWriter)
			res, err = imp.InsertConfig(inputDefine)
			if err != nil {
				return err
			}
		} else {
			imp := val.(impConfigWriterWithContext)
			res, err = imp.InsertConfig(ctx, inputDefine)
			if err != nil {
				return err
			}
		}
		output, err = proto.Marshal(&res)
		if err != nil {
			return err
		}

	case "GetConfigs":
		inputDefine := GetConfigsRequest{}
		if err = proto.Unmarshal(input, &inputDefine); err != nil {
			return err
		}
		var res GetConfigsReply
		if withContext == false {
			imp := val.(impConfigWriter)
			res, err = imp.GetConfigs(inputDefine)
			if err != nil {
				return err
			}
		} else {
			imp := val.(impConfigWriterWithContext)
			res, err = imp.GetConfigs(ctx, inputDefine)
			if err != nil {
				return err
			}
		}
		output, err = proto.Marshal(&res)
		if err != nil {
			return err
		}

	case "UpdateConfig":
		inputDefine := UpdateConfigRequest{}
		if err = proto.Unmarshal(input, &inputDefine); err != nil {
			return err
		}
		var res UpdateConfigReply
		if withContext == false {
			imp := val.(impConfigWriter)
			res, err = imp.UpdateConfig(inputDefine)
			if err != nil {
				return err
			}
		} else {
			imp := val.(impConfigWriterWithContext)
			res, err = imp.UpdateConfig(ctx, inputDefine)
			if err != nil {
				return err
			}
		}
		output, err = proto.Marshal(&res)
		if err != nil {
			return err
		}

	default:
		return fmt.Errorf("func mismatch")
	}
	var _status map[string]string
	s, ok := current.GetResponseStatus(ctx)
	if ok && s != nil {
		_status = s
	}
	var _context map[string]string
	c, ok := current.GetResponseContext(ctx)
	if ok && c != nil {
		_context = c
	}
	*resp = requestf.ResponsePacket{
		IVersion:     1,
		CPacketType:  0,
		IRequestId:   req.IRequestId,
		IMessageType: 0,
		IRet:         0,
		SBuffer:      tools.ByteToInt8(output),
		Status:       _status,
		SResultDesc:  "",
		Context:      _context,
	}
	return nil
}

// InsertConfig is client rpc method as defined
func (obj *ConfigWriter) InsertConfig(input InsertConfigRequest, _opt ...map[string]string) (output InsertConfigReply, err error) {
	ctx := context.Background()
	return obj.InsertConfigWithContext(ctx, input, _opt...)
}

// InsertConfigWithContext is client rpc method as defined
func (obj *ConfigWriter) InsertConfigWithContext(ctx context.Context, input InsertConfigRequest, _opt ...map[string]string) (output InsertConfigReply, err error) {
	var inputMarshal []byte
	inputMarshal, err = proto.Marshal(&input)
	if err != nil {
		return output, err
	}

	var _status map[string]string
	var _context map[string]string
	if len(_opt) == 1 {
		_context = _opt[0]
	} else if len(_opt) == 2 {
		_context = _opt[0]
		_status = _opt[1]
	}

	resp := new(requestf.ResponsePacket)

	err = obj.s.Tars_invoke(ctx, 0, "InsertConfig", inputMarshal, _status, _context, resp)
	if err != nil {
		return output, err
	}
	if err = proto.Unmarshal(tools.Int8ToByte(resp.SBuffer), &output); err != nil {
		return output, err
	}

	if len(_opt) == 1 {
		for k := range _context {
			delete(_context, k)
		}
		for k, v := range resp.Context {
			_context[k] = v
		}
	} else if len(_opt) == 2 {
		for k := range _context {
			delete(_context, k)
		}
		for k, v := range resp.Context {
			_context[k] = v
		}
		for k := range _status {
			delete(_status, k)
		}
		for k, v := range resp.Status {
			_status[k] = v
		}
	}

	return output, nil
}

// GetConfigs is client rpc method as defined
func (obj *ConfigWriter) GetConfigs(input GetConfigsRequest, _opt ...map[string]string) (output GetConfigsReply, err error) {
	ctx := context.Background()
	return obj.GetConfigsWithContext(ctx, input, _opt...)
}

// GetConfigsWithContext is client rpc method as defined
func (obj *ConfigWriter) GetConfigsWithContext(ctx context.Context, input GetConfigsRequest, _opt ...map[string]string) (output GetConfigsReply, err error) {
	var inputMarshal []byte
	inputMarshal, err = proto.Marshal(&input)
	if err != nil {
		return output, err
	}

	var _status map[string]string
	var _context map[string]string
	if len(_opt) == 1 {
		_context = _opt[0]
	} else if len(_opt) == 2 {
		_context = _opt[0]
		_status = _opt[1]
	}

	resp := new(requestf.ResponsePacket)

	err = obj.s.Tars_invoke(ctx, 0, "GetConfigs", inputMarshal, _status, _context, resp)
	if err != nil {
		return output, err
	}
	if err = proto.Unmarshal(tools.Int8ToByte(resp.SBuffer), &output); err != nil {
		return output, err
	}

	if len(_opt) == 1 {
		for k := range _context {
			delete(_context, k)
		}
		for k, v := range resp.Context {
			_context[k] = v
		}
	} else if len(_opt) == 2 {
		for k := range _context {
			delete(_context, k)
		}
		for k, v := range resp.Context {
			_context[k] = v
		}
		for k := range _status {
			delete(_status, k)
		}
		for k, v := range resp.Status {
			_status[k] = v
		}
	}

	return output, nil
}

// UpdateConfig is client rpc method as defined
func (obj *ConfigWriter) UpdateConfig(input UpdateConfigRequest, _opt ...map[string]string) (output UpdateConfigReply, err error) {
	ctx := context.Background()
	return obj.UpdateConfigWithContext(ctx, input, _opt...)
}

// UpdateConfigWithContext is client rpc method as defined
func (obj *ConfigWriter) UpdateConfigWithContext(ctx context.Context, input UpdateConfigRequest, _opt ...map[string]string) (output UpdateConfigReply, err error) {
	var inputMarshal []byte
	inputMarshal, err = proto.Marshal(&input)
	if err != nil {
		return output, err
	}

	var _status map[string]string
	var _context map[string]string
	if len(_opt) == 1 {
		_context = _opt[0]
	} else if len(_opt) == 2 {
		_context = _opt[0]
		_status = _opt[1]
	}

	resp := new(requestf.ResponsePacket)

	err = obj.s.Tars_invoke(ctx, 0, "UpdateConfig", inputMarshal, _status, _context, resp)
	if err != nil {
		return output, err
	}
	if err = proto.Unmarshal(tools.Int8ToByte(resp.SBuffer), &output); err != nil {
		return output, err
	}

	if len(_opt) == 1 {
		for k := range _context {
			delete(_context, k)
		}
		for k, v := range resp.Context {
			_context[k] = v
		}
	} else if len(_opt) == 2 {
		for k := range _context {
			delete(_context, k)
		}
		for k, v := range resp.Context {
			_context[k] = v
		}
		for k := range _status {
			delete(_status, k)
		}
		for k, v := range resp.Status {
			_status[k] = v
		}
	}

	return output, nil
}
