// Code generated by protoc-gen-go. DO NOT EDIT.
// source: project_manager.proto

package project_manager

import (
	context "context"
	fmt "fmt"
	tars "github.com/TarsCloud/TarsGo/tars"
	model "github.com/TarsCloud/TarsGo/tars/model"
	requestf "github.com/TarsCloud/TarsGo/tars/protocol/res/requestf"
	current "github.com/TarsCloud/TarsGo/tars/util/current"
	tools "github.com/TarsCloud/TarsGo/tars/util/tools"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PROJECT_TYPE int32

const (
	// 用于构建平台自身的插件
	PROJECT_TYPE_PLUGIN PROJECT_TYPE = 0
	// 业务项目
	PROJECT_TYPE_BUSINESS PROJECT_TYPE = 1
	// 平台
	PROJECT_TYPE_PLATFORM PROJECT_TYPE = 2
)

var PROJECT_TYPE_name = map[int32]string{
	0: "PLUGIN",
	1: "BUSINESS",
	2: "PLATFORM",
}

var PROJECT_TYPE_value = map[string]int32{
	"PLUGIN":   0,
	"BUSINESS": 1,
	"PLATFORM": 2,
}

func (x PROJECT_TYPE) String() string {
	return proto.EnumName(PROJECT_TYPE_name, int32(x))
}

func (PROJECT_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6a534611bb3d10c3, []int{0}
}

type PROJECT_VISIBILITY int32

const (
	// 开发，产品可见
	PROJECT_VISIBILITY_PRODUCT_OWNER PROJECT_VISIBILITY = 0
	// 所有人可见
	PROJECT_VISIBILITY_PUBLIC PROJECT_VISIBILITY = 1
	// 有权限的可见
	PROJECT_VISIBILITY_HAVE_AUTHORIZATION PROJECT_VISIBILITY = 2
)

var PROJECT_VISIBILITY_name = map[int32]string{
	0: "PRODUCT_OWNER",
	1: "PUBLIC",
	2: "HAVE_AUTHORIZATION",
}

var PROJECT_VISIBILITY_value = map[string]int32{
	"PRODUCT_OWNER":      0,
	"PUBLIC":             1,
	"HAVE_AUTHORIZATION": 2,
}

func (x PROJECT_VISIBILITY) String() string {
	return proto.EnumName(PROJECT_VISIBILITY_name, int32(x))
}

func (PROJECT_VISIBILITY) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6a534611bb3d10c3, []int{1}
}

type PLUGIN_STATUS int32

const (
	PLUGIN_STATUS_ENABLED  PLUGIN_STATUS = 0
	PLUGIN_STATUS_DISABLED PLUGIN_STATUS = 1
)

var PLUGIN_STATUS_name = map[int32]string{
	0: "ENABLED",
	1: "DISABLED",
}

var PLUGIN_STATUS_value = map[string]int32{
	"ENABLED":  0,
	"DISABLED": 1,
}

func (x PLUGIN_STATUS) String() string {
	return proto.EnumName(PLUGIN_STATUS_name, int32(x))
}

func (PLUGIN_STATUS) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6a534611bb3d10c3, []int{2}
}

type Project struct {
	ID                   uint64             `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string             `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Visibility           PROJECT_VISIBILITY `protobuf:"varint,3,opt,name=Visibility,proto3,enum=tars_vcms.project_manager.PROJECT_VISIBILITY" json:"Visibility,omitempty"`
	DevelopersID         []uint64           `protobuf:"varint,4,rep,packed,name=DevelopersID,proto3" json:"DevelopersID,omitempty"`
	PMsID                []uint64           `protobuf:"varint,5,rep,packed,name=PMsID,proto3" json:"PMsID,omitempty"`
	Plugins              []*ProjectPlugin   `protobuf:"bytes,6,rep,name=Plugins,proto3" json:"Plugins,omitempty"`
	CreatedAt            int64              `protobuf:"varint,7,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a534611bb3d10c3, []int{0}
}

func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (m *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(m, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Project) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Project) GetVisibility() PROJECT_VISIBILITY {
	if m != nil {
		return m.Visibility
	}
	return PROJECT_VISIBILITY_PRODUCT_OWNER
}

func (m *Project) GetDevelopersID() []uint64 {
	if m != nil {
		return m.DevelopersID
	}
	return nil
}

func (m *Project) GetPMsID() []uint64 {
	if m != nil {
		return m.PMsID
	}
	return nil
}

func (m *Project) GetPlugins() []*ProjectPlugin {
	if m != nil {
		return m.Plugins
	}
	return nil
}

func (m *Project) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type ProjectPlugin struct {
	ProjectID            uint64            `protobuf:"varint,1,opt,name=ProjectID,proto3" json:"ProjectID,omitempty"`
	PluginID             uint64            `protobuf:"varint,2,opt,name=PluginID,proto3" json:"PluginID,omitempty"`
	PluginInfo           map[string]string `protobuf:"bytes,3,rep,name=PluginInfo,proto3" json:"PluginInfo,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ProjectPlugin) Reset()         { *m = ProjectPlugin{} }
func (m *ProjectPlugin) String() string { return proto.CompactTextString(m) }
func (*ProjectPlugin) ProtoMessage()    {}
func (*ProjectPlugin) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a534611bb3d10c3, []int{1}
}

func (m *ProjectPlugin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectPlugin.Unmarshal(m, b)
}
func (m *ProjectPlugin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectPlugin.Marshal(b, m, deterministic)
}
func (m *ProjectPlugin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectPlugin.Merge(m, src)
}
func (m *ProjectPlugin) XXX_Size() int {
	return xxx_messageInfo_ProjectPlugin.Size(m)
}
func (m *ProjectPlugin) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectPlugin.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectPlugin proto.InternalMessageInfo

func (m *ProjectPlugin) GetProjectID() uint64 {
	if m != nil {
		return m.ProjectID
	}
	return 0
}

func (m *ProjectPlugin) GetPluginID() uint64 {
	if m != nil {
		return m.PluginID
	}
	return 0
}

func (m *ProjectPlugin) GetPluginInfo() map[string]string {
	if m != nil {
		return m.PluginInfo
	}
	return nil
}

type CreateProjectRequest struct {
	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	// 创建者的用户ID 设置为默认开发
	StaffID uint64 `protobuf:"varint,2,opt,name=StaffID,proto3" json:"StaffID,omitempty"`
	// 项目类型，是否为插件
	Type                 PROJECT_TYPE `protobuf:"varint,3,opt,name=Type,proto3,enum=tars_vcms.project_manager.PROJECT_TYPE" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateProjectRequest) Reset()         { *m = CreateProjectRequest{} }
func (m *CreateProjectRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProjectRequest) ProtoMessage()    {}
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a534611bb3d10c3, []int{2}
}

func (m *CreateProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProjectRequest.Unmarshal(m, b)
}
func (m *CreateProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProjectRequest.Marshal(b, m, deterministic)
}
func (m *CreateProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProjectRequest.Merge(m, src)
}
func (m *CreateProjectRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProjectRequest.Size(m)
}
func (m *CreateProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProjectRequest proto.InternalMessageInfo

func (m *CreateProjectRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateProjectRequest) GetStaffID() uint64 {
	if m != nil {
		return m.StaffID
	}
	return 0
}

func (m *CreateProjectRequest) GetType() PROJECT_TYPE {
	if m != nil {
		return m.Type
	}
	return PROJECT_TYPE_PLUGIN
}

type CreateProjectReply struct {
	Project              *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProjectReply) Reset()         { *m = CreateProjectReply{} }
func (m *CreateProjectReply) String() string { return proto.CompactTextString(m) }
func (*CreateProjectReply) ProtoMessage()    {}
func (*CreateProjectReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a534611bb3d10c3, []int{3}
}

func (m *CreateProjectReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProjectReply.Unmarshal(m, b)
}
func (m *CreateProjectReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProjectReply.Marshal(b, m, deterministic)
}
func (m *CreateProjectReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProjectReply.Merge(m, src)
}
func (m *CreateProjectReply) XXX_Size() int {
	return xxx_messageInfo_CreateProjectReply.Size(m)
}
func (m *CreateProjectReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProjectReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProjectReply proto.InternalMessageInfo

func (m *CreateProjectReply) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type DeleteProjectRequest struct {
	// 删除的项目ID
	ProjectID uint64 `protobuf:"varint,1,opt,name=ProjectID,proto3" json:"ProjectID,omitempty"`
	// 操作人的ID
	StaffID              uint64   `protobuf:"varint,2,opt,name=StaffID,proto3" json:"StaffID,omitempty"`
	Reason               string   `protobuf:"bytes,3,opt,name=Reason,proto3" json:"Reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteProjectRequest) Reset()         { *m = DeleteProjectRequest{} }
func (m *DeleteProjectRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteProjectRequest) ProtoMessage()    {}
func (*DeleteProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a534611bb3d10c3, []int{4}
}

func (m *DeleteProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProjectRequest.Unmarshal(m, b)
}
func (m *DeleteProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProjectRequest.Marshal(b, m, deterministic)
}
func (m *DeleteProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProjectRequest.Merge(m, src)
}
func (m *DeleteProjectRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteProjectRequest.Size(m)
}
func (m *DeleteProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProjectRequest proto.InternalMessageInfo

func (m *DeleteProjectRequest) GetProjectID() uint64 {
	if m != nil {
		return m.ProjectID
	}
	return 0
}

func (m *DeleteProjectRequest) GetStaffID() uint64 {
	if m != nil {
		return m.StaffID
	}
	return 0
}

func (m *DeleteProjectRequest) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type DeleteProjectReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteProjectReply) Reset()         { *m = DeleteProjectReply{} }
func (m *DeleteProjectReply) String() string { return proto.CompactTextString(m) }
func (*DeleteProjectReply) ProtoMessage()    {}
func (*DeleteProjectReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a534611bb3d10c3, []int{5}
}

func (m *DeleteProjectReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProjectReply.Unmarshal(m, b)
}
func (m *DeleteProjectReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProjectReply.Marshal(b, m, deterministic)
}
func (m *DeleteProjectReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProjectReply.Merge(m, src)
}
func (m *DeleteProjectReply) XXX_Size() int {
	return xxx_messageInfo_DeleteProjectReply.Size(m)
}
func (m *DeleteProjectReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProjectReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProjectReply proto.InternalMessageInfo

type GetProjectsRequest struct {
	// 为空表示根据其他条件搜索
	StaffID uint64 `protobuf:"varint,1,opt,name=StaffID,proto3" json:"StaffID,omitempty"`
	// 为空表示根据其他条件搜索
	ProjectID            []uint64 `protobuf:"varint,2,rep,packed,name=ProjectID,proto3" json:"ProjectID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProjectsRequest) Reset()         { *m = GetProjectsRequest{} }
func (m *GetProjectsRequest) String() string { return proto.CompactTextString(m) }
func (*GetProjectsRequest) ProtoMessage()    {}
func (*GetProjectsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a534611bb3d10c3, []int{6}
}

func (m *GetProjectsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProjectsRequest.Unmarshal(m, b)
}
func (m *GetProjectsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProjectsRequest.Marshal(b, m, deterministic)
}
func (m *GetProjectsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProjectsRequest.Merge(m, src)
}
func (m *GetProjectsRequest) XXX_Size() int {
	return xxx_messageInfo_GetProjectsRequest.Size(m)
}
func (m *GetProjectsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProjectsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProjectsRequest proto.InternalMessageInfo

func (m *GetProjectsRequest) GetStaffID() uint64 {
	if m != nil {
		return m.StaffID
	}
	return 0
}

func (m *GetProjectsRequest) GetProjectID() []uint64 {
	if m != nil {
		return m.ProjectID
	}
	return nil
}

type GetProjectsReply struct {
	Projects             []*Project `protobuf:"bytes,1,rep,name=Projects,proto3" json:"Projects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetProjectsReply) Reset()         { *m = GetProjectsReply{} }
func (m *GetProjectsReply) String() string { return proto.CompactTextString(m) }
func (*GetProjectsReply) ProtoMessage()    {}
func (*GetProjectsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a534611bb3d10c3, []int{7}
}

func (m *GetProjectsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProjectsReply.Unmarshal(m, b)
}
func (m *GetProjectsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProjectsReply.Marshal(b, m, deterministic)
}
func (m *GetProjectsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProjectsReply.Merge(m, src)
}
func (m *GetProjectsReply) XXX_Size() int {
	return xxx_messageInfo_GetProjectsReply.Size(m)
}
func (m *GetProjectsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProjectsReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetProjectsReply proto.InternalMessageInfo

func (m *GetProjectsReply) GetProjects() []*Project {
	if m != nil {
		return m.Projects
	}
	return nil
}

type SetProjectStaffRequest struct {
	// 操作人ID
	StaffID              uint64   `protobuf:"varint,1,opt,name=StaffID,proto3" json:"StaffID,omitempty"`
	DevelopersID         []uint64 `protobuf:"varint,2,rep,packed,name=DevelopersID,proto3" json:"DevelopersID,omitempty"`
	PMsID                []uint64 `protobuf:"varint,3,rep,packed,name=PMsID,proto3" json:"PMsID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetProjectStaffRequest) Reset()         { *m = SetProjectStaffRequest{} }
func (m *SetProjectStaffRequest) String() string { return proto.CompactTextString(m) }
func (*SetProjectStaffRequest) ProtoMessage()    {}
func (*SetProjectStaffRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a534611bb3d10c3, []int{8}
}

func (m *SetProjectStaffRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetProjectStaffRequest.Unmarshal(m, b)
}
func (m *SetProjectStaffRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetProjectStaffRequest.Marshal(b, m, deterministic)
}
func (m *SetProjectStaffRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetProjectStaffRequest.Merge(m, src)
}
func (m *SetProjectStaffRequest) XXX_Size() int {
	return xxx_messageInfo_SetProjectStaffRequest.Size(m)
}
func (m *SetProjectStaffRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetProjectStaffRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetProjectStaffRequest proto.InternalMessageInfo

func (m *SetProjectStaffRequest) GetStaffID() uint64 {
	if m != nil {
		return m.StaffID
	}
	return 0
}

func (m *SetProjectStaffRequest) GetDevelopersID() []uint64 {
	if m != nil {
		return m.DevelopersID
	}
	return nil
}

func (m *SetProjectStaffRequest) GetPMsID() []uint64 {
	if m != nil {
		return m.PMsID
	}
	return nil
}

type SetProjectStaffReply struct {
	Project              *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetProjectStaffReply) Reset()         { *m = SetProjectStaffReply{} }
func (m *SetProjectStaffReply) String() string { return proto.CompactTextString(m) }
func (*SetProjectStaffReply) ProtoMessage()    {}
func (*SetProjectStaffReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a534611bb3d10c3, []int{9}
}

func (m *SetProjectStaffReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetProjectStaffReply.Unmarshal(m, b)
}
func (m *SetProjectStaffReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetProjectStaffReply.Marshal(b, m, deterministic)
}
func (m *SetProjectStaffReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetProjectStaffReply.Merge(m, src)
}
func (m *SetProjectStaffReply) XXX_Size() int {
	return xxx_messageInfo_SetProjectStaffReply.Size(m)
}
func (m *SetProjectStaffReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SetProjectStaffReply.DiscardUnknown(m)
}

var xxx_messageInfo_SetProjectStaffReply proto.InternalMessageInfo

func (m *SetProjectStaffReply) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type SetProjectPluginRequest struct {
	ProjectID uint64        `protobuf:"varint,1,opt,name=ProjectID,proto3" json:"ProjectID,omitempty"`
	Status    PLUGIN_STATUS `protobuf:"varint,2,opt,name=Status,proto3,enum=tars_vcms.project_manager.PLUGIN_STATUS" json:"Status,omitempty"`
	// 操作者ID
	StaffID              uint64            `protobuf:"varint,3,opt,name=StaffID,proto3" json:"StaffID,omitempty"`
	PluginInfo           map[string]string `protobuf:"bytes,4,rep,name=PluginInfo,proto3" json:"PluginInfo,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SetProjectPluginRequest) Reset()         { *m = SetProjectPluginRequest{} }
func (m *SetProjectPluginRequest) String() string { return proto.CompactTextString(m) }
func (*SetProjectPluginRequest) ProtoMessage()    {}
func (*SetProjectPluginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a534611bb3d10c3, []int{10}
}

func (m *SetProjectPluginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetProjectPluginRequest.Unmarshal(m, b)
}
func (m *SetProjectPluginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetProjectPluginRequest.Marshal(b, m, deterministic)
}
func (m *SetProjectPluginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetProjectPluginRequest.Merge(m, src)
}
func (m *SetProjectPluginRequest) XXX_Size() int {
	return xxx_messageInfo_SetProjectPluginRequest.Size(m)
}
func (m *SetProjectPluginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetProjectPluginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetProjectPluginRequest proto.InternalMessageInfo

func (m *SetProjectPluginRequest) GetProjectID() uint64 {
	if m != nil {
		return m.ProjectID
	}
	return 0
}

func (m *SetProjectPluginRequest) GetStatus() PLUGIN_STATUS {
	if m != nil {
		return m.Status
	}
	return PLUGIN_STATUS_ENABLED
}

func (m *SetProjectPluginRequest) GetStaffID() uint64 {
	if m != nil {
		return m.StaffID
	}
	return 0
}

func (m *SetProjectPluginRequest) GetPluginInfo() map[string]string {
	if m != nil {
		return m.PluginInfo
	}
	return nil
}

type SetProjectPluginReply struct {
	Plugin               *ProjectPlugin `protobuf:"bytes,1,opt,name=Plugin,proto3" json:"Plugin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SetProjectPluginReply) Reset()         { *m = SetProjectPluginReply{} }
func (m *SetProjectPluginReply) String() string { return proto.CompactTextString(m) }
func (*SetProjectPluginReply) ProtoMessage()    {}
func (*SetProjectPluginReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a534611bb3d10c3, []int{11}
}

func (m *SetProjectPluginReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetProjectPluginReply.Unmarshal(m, b)
}
func (m *SetProjectPluginReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetProjectPluginReply.Marshal(b, m, deterministic)
}
func (m *SetProjectPluginReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetProjectPluginReply.Merge(m, src)
}
func (m *SetProjectPluginReply) XXX_Size() int {
	return xxx_messageInfo_SetProjectPluginReply.Size(m)
}
func (m *SetProjectPluginReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SetProjectPluginReply.DiscardUnknown(m)
}

var xxx_messageInfo_SetProjectPluginReply proto.InternalMessageInfo

func (m *SetProjectPluginReply) GetPlugin() *ProjectPlugin {
	if m != nil {
		return m.Plugin
	}
	return nil
}

func init() {
	proto.RegisterEnum("tars_vcms.project_manager.PROJECT_TYPE", PROJECT_TYPE_name, PROJECT_TYPE_value)
	proto.RegisterEnum("tars_vcms.project_manager.PROJECT_VISIBILITY", PROJECT_VISIBILITY_name, PROJECT_VISIBILITY_value)
	proto.RegisterEnum("tars_vcms.project_manager.PLUGIN_STATUS", PLUGIN_STATUS_name, PLUGIN_STATUS_value)
	proto.RegisterType((*Project)(nil), "tars_vcms.project_manager.Project")
	proto.RegisterType((*ProjectPlugin)(nil), "tars_vcms.project_manager.ProjectPlugin")
	proto.RegisterMapType((map[string]string)(nil), "tars_vcms.project_manager.ProjectPlugin.PluginInfoEntry")
	proto.RegisterType((*CreateProjectRequest)(nil), "tars_vcms.project_manager.CreateProjectRequest")
	proto.RegisterType((*CreateProjectReply)(nil), "tars_vcms.project_manager.CreateProjectReply")
	proto.RegisterType((*DeleteProjectRequest)(nil), "tars_vcms.project_manager.DeleteProjectRequest")
	proto.RegisterType((*DeleteProjectReply)(nil), "tars_vcms.project_manager.DeleteProjectReply")
	proto.RegisterType((*GetProjectsRequest)(nil), "tars_vcms.project_manager.GetProjectsRequest")
	proto.RegisterType((*GetProjectsReply)(nil), "tars_vcms.project_manager.GetProjectsReply")
	proto.RegisterType((*SetProjectStaffRequest)(nil), "tars_vcms.project_manager.SetProjectStaffRequest")
	proto.RegisterType((*SetProjectStaffReply)(nil), "tars_vcms.project_manager.SetProjectStaffReply")
	proto.RegisterType((*SetProjectPluginRequest)(nil), "tars_vcms.project_manager.SetProjectPluginRequest")
	proto.RegisterMapType((map[string]string)(nil), "tars_vcms.project_manager.SetProjectPluginRequest.PluginInfoEntry")
	proto.RegisterType((*SetProjectPluginReply)(nil), "tars_vcms.project_manager.SetProjectPluginReply")
}

func init() { proto.RegisterFile("project_manager.proto", fileDescriptor_6a534611bb3d10c3) }

var fileDescriptor_6a534611bb3d10c3 = []byte{
	// 793 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x5b, 0x6e, 0xda, 0x40,
	0x14, 0x8d, 0x1f, 0x81, 0x70, 0x09, 0xc4, 0x19, 0x91, 0xd4, 0x45, 0xfd, 0x40, 0xfe, 0x29, 0xa2,
	0x0a, 0x69, 0xa9, 0x54, 0x45, 0x7d, 0x29, 0x80, 0xdd, 0xc4, 0x2d, 0x2f, 0x8d, 0x4d, 0xda, 0xe4,
	0x07, 0x39, 0xe9, 0x10, 0xd1, 0x3a, 0x98, 0x62, 0x13, 0x95, 0xcf, 0xee, 0xa2, 0x2b, 0xe9, 0x32,
	0xba, 0x88, 0xae, 0xa4, 0xf2, 0xd8, 0x80, 0x6d, 0x12, 0x87, 0xa8, 0xea, 0x9f, 0xef, 0x9d, 0x39,
	0xf7, 0x75, 0xe6, 0x1e, 0x80, 0x9d, 0xd1, 0xd8, 0xfa, 0x42, 0x2e, 0x9c, 0xde, 0x95, 0x31, 0x34,
	0x2e, 0xc9, 0xb8, 0x3c, 0x1a, 0x5b, 0x8e, 0x85, 0x1e, 0x3a, 0xc6, 0xd8, 0xee, 0x5d, 0x5f, 0x5c,
	0xd9, 0xe5, 0xc8, 0x05, 0xe9, 0x27, 0x0b, 0xc9, 0x8e, 0xe7, 0x43, 0x59, 0x60, 0x55, 0x59, 0x64,
	0x0a, 0x4c, 0x91, 0xc7, 0xac, 0x2a, 0x23, 0x04, 0x7c, 0xcb, 0xb8, 0x22, 0x22, 0x5b, 0x60, 0x8a,
	0x29, 0x4c, 0xbf, 0x51, 0x13, 0xe0, 0x64, 0x60, 0x0f, 0xce, 0x07, 0xe6, 0xc0, 0x99, 0x8a, 0x5c,
	0x81, 0x29, 0x66, 0x2b, 0x7b, 0xe5, 0x5b, 0xe3, 0x97, 0x3b, 0xb8, 0xfd, 0x5e, 0xa9, 0xeb, 0xbd,
	0x13, 0x55, 0x53, 0x6b, 0x6a, 0x43, 0xd5, 0x4f, 0x71, 0x20, 0x00, 0x92, 0x60, 0x53, 0x26, 0xd7,
	0xc4, 0xb4, 0x46, 0x64, 0x6c, 0xab, 0xb2, 0xc8, 0x17, 0xb8, 0x22, 0x8f, 0x43, 0x3e, 0x94, 0x83,
	0xf5, 0x4e, 0xd3, 0x3d, 0x5c, 0xa7, 0x87, 0x9e, 0x81, 0x6a, 0x90, 0xec, 0x98, 0x93, 0xcb, 0xc1,
	0xd0, 0x16, 0x13, 0x05, 0xae, 0x98, 0xae, 0x14, 0xe3, 0xaa, 0xf0, 0x6c, 0x0f, 0x80, 0x67, 0x40,
	0xf4, 0x08, 0x52, 0xf5, 0x31, 0x31, 0x1c, 0xf2, 0xb9, 0xea, 0x88, 0xc9, 0x02, 0x53, 0xe4, 0xf0,
	0xc2, 0x21, 0xfd, 0x61, 0x20, 0x13, 0x02, 0xba, 0xf7, 0x7d, 0xc7, 0x7c, 0x4e, 0x0b, 0x07, 0xca,
	0xc3, 0x86, 0x77, 0x4f, 0x95, 0xe9, 0xc8, 0x78, 0x3c, 0xb7, 0xd1, 0x27, 0x00, 0xff, 0x7b, 0xd8,
	0xb7, 0x44, 0x8e, 0x16, 0x7c, 0xb0, 0x6a, 0xc1, 0xe5, 0x05, 0x54, 0x19, 0x3a, 0xe3, 0x29, 0x0e,
	0xc4, 0xca, 0xbf, 0x81, 0xad, 0xc8, 0x31, 0x12, 0x80, 0xfb, 0x4a, 0xa6, 0xb4, 0xc0, 0x14, 0x76,
	0x3f, 0xdd, 0x11, 0x5e, 0x1b, 0xe6, 0x64, 0x46, 0xa5, 0x67, 0xbc, 0x64, 0x0f, 0x18, 0xe9, 0x07,
	0x03, 0x39, 0xaf, 0x65, 0x3f, 0x25, 0x26, 0xdf, 0x26, 0xc4, 0x76, 0xe6, 0xe4, 0x33, 0x01, 0xf2,
	0x45, 0x48, 0x6a, 0x8e, 0xd1, 0xef, 0xcf, 0x1b, 0x9c, 0x99, 0xe8, 0x15, 0xf0, 0xfa, 0x74, 0x44,
	0xfc, 0x07, 0xf1, 0x78, 0x85, 0x07, 0xa1, 0x9f, 0x76, 0x14, 0x4c, 0x41, 0x12, 0x06, 0x14, 0x29,
	0x61, 0x64, 0x4e, 0xd1, 0x6b, 0x48, 0xfa, 0x58, 0x5a, 0x43, 0xba, 0x22, 0xdd, 0x3d, 0x2f, 0x3c,
	0x83, 0x48, 0x7d, 0xc8, 0xc9, 0xc4, 0x24, 0x4b, 0x6d, 0xc5, 0x53, 0x78, 0x7b, 0x83, 0xbb, 0x90,
	0xc0, 0xc4, 0xb0, 0xad, 0x21, 0x6d, 0x31, 0x85, 0x7d, 0x4b, 0xca, 0x01, 0x8a, 0xe4, 0x19, 0x99,
	0x53, 0xa9, 0x01, 0xe8, 0x88, 0x38, 0xbe, 0xcb, 0x9e, 0xe5, 0x0e, 0x44, 0x67, 0xc2, 0xd1, 0x43,
	0x55, 0xb1, 0xf4, 0x99, 0x2f, 0x1c, 0x12, 0x06, 0x21, 0x14, 0xcd, 0x9d, 0xce, 0x5b, 0xd8, 0x98,
	0x39, 0x44, 0x86, 0x3e, 0xa7, 0x55, 0xc6, 0x33, 0xc7, 0x48, 0x26, 0xec, 0x6a, 0xf3, 0x98, 0xb4,
	0x8c, 0xbb, 0xab, 0x8c, 0x2e, 0x2b, 0x1b, 0xb7, 0xac, 0x5c, 0x60, 0x59, 0x25, 0x1d, 0x72, 0x4b,
	0xd9, 0xfe, 0x9d, 0xe3, 0x5f, 0x2c, 0x3c, 0x58, 0x84, 0xf5, 0x97, 0x7b, 0x25, 0x9e, 0x0f, 0x21,
	0xa1, 0x39, 0x86, 0x33, 0xb1, 0x29, 0xcd, 0xd9, 0x78, 0xed, 0x68, 0x74, 0x8f, 0xd4, 0x56, 0x4f,
	0xd3, 0xab, 0x7a, 0x57, 0xc3, 0x3e, 0x2e, 0x38, 0x25, 0x2e, 0x3c, 0xa5, 0xf3, 0xd0, 0xaa, 0xf3,
	0x94, 0x9b, 0x5a, 0x4c, 0xfc, 0x5b, 0x3a, 0xf8, 0x9f, 0x4b, 0x7f, 0x0a, 0x3b, 0xcb, 0x59, 0x5d,
	0x3e, 0x0e, 0x21, 0xe1, 0x99, 0x3e, 0x1d, 0xab, 0x6b, 0xaa, 0x8f, 0x2b, 0xbd, 0x80, 0xcd, 0xe0,
	0x86, 0x23, 0x80, 0x84, 0x37, 0x40, 0x61, 0x0d, 0x6d, 0xc2, 0x46, 0xad, 0xab, 0xa9, 0x2d, 0x45,
	0xd3, 0x04, 0xc6, 0xb5, 0x3a, 0x8d, 0xaa, 0xfe, 0xae, 0x8d, 0x9b, 0x02, 0x5b, 0xfa, 0x00, 0x68,
	0xf9, 0xa7, 0x02, 0x6d, 0x43, 0xa6, 0x83, 0xdb, 0x72, 0xb7, 0xae, 0xf7, 0xda, 0x1f, 0x5b, 0x0a,
	0x16, 0xd6, 0x68, 0xc0, 0x6e, 0xad, 0xa1, 0xd6, 0x05, 0x06, 0xed, 0x02, 0x3a, 0xae, 0x9e, 0x28,
	0xbd, 0x6a, 0x57, 0x3f, 0x6e, 0x63, 0xf5, 0xac, 0xaa, 0xab, 0xed, 0x96, 0xc0, 0x96, 0x4a, 0x90,
	0x09, 0xb1, 0x86, 0xd2, 0x90, 0x54, 0x5a, 0xd5, 0x5a, 0x43, 0x91, 0xbd, 0x32, 0x64, 0x55, 0xf3,
	0x2c, 0xa6, 0xf2, 0x9b, 0x87, 0xac, 0xdf, 0x4a, 0xd3, 0xeb, 0x0c, 0x59, 0x90, 0x09, 0xe9, 0x11,
	0xda, 0x8f, 0x19, 0xc3, 0x4d, 0xe2, 0x99, 0xdf, 0x5b, 0x1d, 0xe0, 0x8e, 0xdd, 0x82, 0x4c, 0x48,
	0x44, 0x62, 0x13, 0xde, 0x24, 0x6b, 0xb1, 0x09, 0x97, 0xf5, 0x09, 0x0d, 0x20, 0x1d, 0x50, 0x14,
	0xf4, 0x24, 0x06, 0x1d, 0x55, 0x9e, 0xd8, 0x54, 0x37, 0x88, 0xde, 0x04, 0xb6, 0x22, 0xab, 0x8f,
	0x9e, 0xad, 0xb4, 0x0d, 0x41, 0x51, 0xca, 0xef, 0xdf, 0x07, 0xe2, 0x76, 0xf8, 0x1d, 0x84, 0xe8,
	0x13, 0x47, 0x95, 0xfb, 0x6f, 0x61, 0xfe, 0xe9, 0xbd, 0x30, 0x23, 0x73, 0x5a, 0xdb, 0x3e, 0xdb,
	0xf2, 0x2f, 0xee, 0xf9, 0x17, 0xcf, 0x13, 0xf4, 0x6f, 0xd8, 0xf3, 0xbf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x3b, 0xed, 0xad, 0x53, 0x9f, 0x09, 0x00, 0x00,
}

// This following code was generated by tarsrpc
// Gernerated from project_manager.proto
type ProjectManager struct {
	s model.Servant
}

//SetServant is required by the servant interface.
func (obj *ProjectManager) SetServant(s model.Servant) {
	obj.s = s
}

//AddServant is required by the servant interface
func (obj *ProjectManager) AddServant(imp impProjectManager, objStr string) {
	tars.AddServant(obj, imp, objStr)
}

////AddServant adds servant  for the service with context
func (obj *ProjectManager) AddServantWithContext(imp impProjectManagerWithContext, objStr string) {
	tars.AddServantWithContext(obj, imp, objStr)
}

//TarsSetTimeout is required by the servant interface. t is the timeout in ms.
func (obj *ProjectManager) TarsSetTimeout(t int) {
	obj.s.TarsSetTimeout(t)
}

//TarsSetProtocol is required by the servant interface. t is the protocol.
func (obj *ProjectManager) TarsSetProtocol(p model.Protocol) {
	obj.s.TarsSetProtocol(p)
}

type impProjectManager interface {
	CreateProject(input CreateProjectRequest) (output CreateProjectReply, err error)
	DeleteProject(input DeleteProjectRequest) (output DeleteProjectReply, err error)
	GetProjects(input GetProjectsReply) (output GetProjectsRequest, err error)
	SetProjectStaff(input SetProjectStaffRequest) (output SetProjectStaffReply, err error)
	SetProjectPlugin(input SetProjectPluginRequest) (output SetProjectPluginReply, err error)
}

type impProjectManagerWithContext interface {
	CreateProject(ctx context.Context, input CreateProjectRequest) (output CreateProjectReply, err error)
	DeleteProject(ctx context.Context, input DeleteProjectRequest) (output DeleteProjectReply, err error)
	GetProjects(ctx context.Context, input GetProjectsReply) (output GetProjectsRequest, err error)
	SetProjectStaff(ctx context.Context, input SetProjectStaffRequest) (output SetProjectStaffReply, err error)
	SetProjectPlugin(ctx context.Context, input SetProjectPluginRequest) (output SetProjectPluginReply, err error)
}

//Dispatch is used to call the user implement of the defined method.
func (obj *ProjectManager) Dispatch(ctx context.Context, val interface{}, req *requestf.RequestPacket, resp *requestf.ResponsePacket, withContext bool) (err error) {
	input := tools.Int8ToByte(req.SBuffer)
	var output []byte
	funcName := req.SFuncName
	switch funcName {

	case "CreateProject":
		inputDefine := CreateProjectRequest{}
		if err = proto.Unmarshal(input, &inputDefine); err != nil {
			return err
		}
		var res CreateProjectReply
		if withContext == false {
			imp := val.(impProjectManager)
			res, err = imp.CreateProject(inputDefine)
			if err != nil {
				return err
			}
		} else {
			imp := val.(impProjectManagerWithContext)
			res, err = imp.CreateProject(ctx, inputDefine)
			if err != nil {
				return err
			}
		}
		output, err = proto.Marshal(&res)
		if err != nil {
			return err
		}

	case "DeleteProject":
		inputDefine := DeleteProjectRequest{}
		if err = proto.Unmarshal(input, &inputDefine); err != nil {
			return err
		}
		var res DeleteProjectReply
		if withContext == false {
			imp := val.(impProjectManager)
			res, err = imp.DeleteProject(inputDefine)
			if err != nil {
				return err
			}
		} else {
			imp := val.(impProjectManagerWithContext)
			res, err = imp.DeleteProject(ctx, inputDefine)
			if err != nil {
				return err
			}
		}
		output, err = proto.Marshal(&res)
		if err != nil {
			return err
		}

	case "GetProjects":
		inputDefine := GetProjectsReply{}
		if err = proto.Unmarshal(input, &inputDefine); err != nil {
			return err
		}
		var res GetProjectsRequest
		if withContext == false {
			imp := val.(impProjectManager)
			res, err = imp.GetProjects(inputDefine)
			if err != nil {
				return err
			}
		} else {
			imp := val.(impProjectManagerWithContext)
			res, err = imp.GetProjects(ctx, inputDefine)
			if err != nil {
				return err
			}
		}
		output, err = proto.Marshal(&res)
		if err != nil {
			return err
		}

	case "SetProjectStaff":
		inputDefine := SetProjectStaffRequest{}
		if err = proto.Unmarshal(input, &inputDefine); err != nil {
			return err
		}
		var res SetProjectStaffReply
		if withContext == false {
			imp := val.(impProjectManager)
			res, err = imp.SetProjectStaff(inputDefine)
			if err != nil {
				return err
			}
		} else {
			imp := val.(impProjectManagerWithContext)
			res, err = imp.SetProjectStaff(ctx, inputDefine)
			if err != nil {
				return err
			}
		}
		output, err = proto.Marshal(&res)
		if err != nil {
			return err
		}

	case "SetProjectPlugin":
		inputDefine := SetProjectPluginRequest{}
		if err = proto.Unmarshal(input, &inputDefine); err != nil {
			return err
		}
		var res SetProjectPluginReply
		if withContext == false {
			imp := val.(impProjectManager)
			res, err = imp.SetProjectPlugin(inputDefine)
			if err != nil {
				return err
			}
		} else {
			imp := val.(impProjectManagerWithContext)
			res, err = imp.SetProjectPlugin(ctx, inputDefine)
			if err != nil {
				return err
			}
		}
		output, err = proto.Marshal(&res)
		if err != nil {
			return err
		}

	default:
		return fmt.Errorf("func mismatch")
	}
	var _status map[string]string
	s, ok := current.GetResponseStatus(ctx)
	if ok && s != nil {
		_status = s
	}
	var _context map[string]string
	c, ok := current.GetResponseContext(ctx)
	if ok && c != nil {
		_context = c
	}
	*resp = requestf.ResponsePacket{
		IVersion:     1,
		CPacketType:  0,
		IRequestId:   req.IRequestId,
		IMessageType: 0,
		IRet:         0,
		SBuffer:      tools.ByteToInt8(output),
		Status:       _status,
		SResultDesc:  "",
		Context:      _context,
	}
	return nil
}

// CreateProject is client rpc method as defined
func (obj *ProjectManager) CreateProject(input CreateProjectRequest, _opt ...map[string]string) (output CreateProjectReply, err error) {
	ctx := context.Background()
	return obj.CreateProjectWithContext(ctx, input, _opt...)
}

// CreateProjectWithContext is client rpc method as defined
func (obj *ProjectManager) CreateProjectWithContext(ctx context.Context, input CreateProjectRequest, _opt ...map[string]string) (output CreateProjectReply, err error) {
	var inputMarshal []byte
	inputMarshal, err = proto.Marshal(&input)
	if err != nil {
		return output, err
	}

	var _status map[string]string
	var _context map[string]string
	if len(_opt) == 1 {
		_context = _opt[0]
	} else if len(_opt) == 2 {
		_context = _opt[0]
		_status = _opt[1]
	}

	resp := new(requestf.ResponsePacket)

	err = obj.s.Tars_invoke(ctx, 0, "CreateProject", inputMarshal, _status, _context, resp)
	if err != nil {
		return output, err
	}
	if err = proto.Unmarshal(tools.Int8ToByte(resp.SBuffer), &output); err != nil {
		return output, err
	}

	if len(_opt) == 1 {
		for k := range _context {
			delete(_context, k)
		}
		for k, v := range resp.Context {
			_context[k] = v
		}
	} else if len(_opt) == 2 {
		for k := range _context {
			delete(_context, k)
		}
		for k, v := range resp.Context {
			_context[k] = v
		}
		for k := range _status {
			delete(_status, k)
		}
		for k, v := range resp.Status {
			_status[k] = v
		}
	}

	return output, nil
}

// DeleteProject is client rpc method as defined
func (obj *ProjectManager) DeleteProject(input DeleteProjectRequest, _opt ...map[string]string) (output DeleteProjectReply, err error) {
	ctx := context.Background()
	return obj.DeleteProjectWithContext(ctx, input, _opt...)
}

// DeleteProjectWithContext is client rpc method as defined
func (obj *ProjectManager) DeleteProjectWithContext(ctx context.Context, input DeleteProjectRequest, _opt ...map[string]string) (output DeleteProjectReply, err error) {
	var inputMarshal []byte
	inputMarshal, err = proto.Marshal(&input)
	if err != nil {
		return output, err
	}

	var _status map[string]string
	var _context map[string]string
	if len(_opt) == 1 {
		_context = _opt[0]
	} else if len(_opt) == 2 {
		_context = _opt[0]
		_status = _opt[1]
	}

	resp := new(requestf.ResponsePacket)

	err = obj.s.Tars_invoke(ctx, 0, "DeleteProject", inputMarshal, _status, _context, resp)
	if err != nil {
		return output, err
	}
	if err = proto.Unmarshal(tools.Int8ToByte(resp.SBuffer), &output); err != nil {
		return output, err
	}

	if len(_opt) == 1 {
		for k := range _context {
			delete(_context, k)
		}
		for k, v := range resp.Context {
			_context[k] = v
		}
	} else if len(_opt) == 2 {
		for k := range _context {
			delete(_context, k)
		}
		for k, v := range resp.Context {
			_context[k] = v
		}
		for k := range _status {
			delete(_status, k)
		}
		for k, v := range resp.Status {
			_status[k] = v
		}
	}

	return output, nil
}

// GetProjects is client rpc method as defined
func (obj *ProjectManager) GetProjects(input GetProjectsReply, _opt ...map[string]string) (output GetProjectsRequest, err error) {
	ctx := context.Background()
	return obj.GetProjectsWithContext(ctx, input, _opt...)
}

// GetProjectsWithContext is client rpc method as defined
func (obj *ProjectManager) GetProjectsWithContext(ctx context.Context, input GetProjectsReply, _opt ...map[string]string) (output GetProjectsRequest, err error) {
	var inputMarshal []byte
	inputMarshal, err = proto.Marshal(&input)
	if err != nil {
		return output, err
	}

	var _status map[string]string
	var _context map[string]string
	if len(_opt) == 1 {
		_context = _opt[0]
	} else if len(_opt) == 2 {
		_context = _opt[0]
		_status = _opt[1]
	}

	resp := new(requestf.ResponsePacket)

	err = obj.s.Tars_invoke(ctx, 0, "GetProjects", inputMarshal, _status, _context, resp)
	if err != nil {
		return output, err
	}
	if err = proto.Unmarshal(tools.Int8ToByte(resp.SBuffer), &output); err != nil {
		return output, err
	}

	if len(_opt) == 1 {
		for k := range _context {
			delete(_context, k)
		}
		for k, v := range resp.Context {
			_context[k] = v
		}
	} else if len(_opt) == 2 {
		for k := range _context {
			delete(_context, k)
		}
		for k, v := range resp.Context {
			_context[k] = v
		}
		for k := range _status {
			delete(_status, k)
		}
		for k, v := range resp.Status {
			_status[k] = v
		}
	}

	return output, nil
}

// SetProjectStaff is client rpc method as defined
func (obj *ProjectManager) SetProjectStaff(input SetProjectStaffRequest, _opt ...map[string]string) (output SetProjectStaffReply, err error) {
	ctx := context.Background()
	return obj.SetProjectStaffWithContext(ctx, input, _opt...)
}

// SetProjectStaffWithContext is client rpc method as defined
func (obj *ProjectManager) SetProjectStaffWithContext(ctx context.Context, input SetProjectStaffRequest, _opt ...map[string]string) (output SetProjectStaffReply, err error) {
	var inputMarshal []byte
	inputMarshal, err = proto.Marshal(&input)
	if err != nil {
		return output, err
	}

	var _status map[string]string
	var _context map[string]string
	if len(_opt) == 1 {
		_context = _opt[0]
	} else if len(_opt) == 2 {
		_context = _opt[0]
		_status = _opt[1]
	}

	resp := new(requestf.ResponsePacket)

	err = obj.s.Tars_invoke(ctx, 0, "SetProjectStaff", inputMarshal, _status, _context, resp)
	if err != nil {
		return output, err
	}
	if err = proto.Unmarshal(tools.Int8ToByte(resp.SBuffer), &output); err != nil {
		return output, err
	}

	if len(_opt) == 1 {
		for k := range _context {
			delete(_context, k)
		}
		for k, v := range resp.Context {
			_context[k] = v
		}
	} else if len(_opt) == 2 {
		for k := range _context {
			delete(_context, k)
		}
		for k, v := range resp.Context {
			_context[k] = v
		}
		for k := range _status {
			delete(_status, k)
		}
		for k, v := range resp.Status {
			_status[k] = v
		}
	}

	return output, nil
}

// SetProjectPlugin is client rpc method as defined
func (obj *ProjectManager) SetProjectPlugin(input SetProjectPluginRequest, _opt ...map[string]string) (output SetProjectPluginReply, err error) {
	ctx := context.Background()
	return obj.SetProjectPluginWithContext(ctx, input, _opt...)
}

// SetProjectPluginWithContext is client rpc method as defined
func (obj *ProjectManager) SetProjectPluginWithContext(ctx context.Context, input SetProjectPluginRequest, _opt ...map[string]string) (output SetProjectPluginReply, err error) {
	var inputMarshal []byte
	inputMarshal, err = proto.Marshal(&input)
	if err != nil {
		return output, err
	}

	var _status map[string]string
	var _context map[string]string
	if len(_opt) == 1 {
		_context = _opt[0]
	} else if len(_opt) == 2 {
		_context = _opt[0]
		_status = _opt[1]
	}

	resp := new(requestf.ResponsePacket)

	err = obj.s.Tars_invoke(ctx, 0, "SetProjectPlugin", inputMarshal, _status, _context, resp)
	if err != nil {
		return output, err
	}
	if err = proto.Unmarshal(tools.Int8ToByte(resp.SBuffer), &output); err != nil {
		return output, err
	}

	if len(_opt) == 1 {
		for k := range _context {
			delete(_context, k)
		}
		for k, v := range resp.Context {
			_context[k] = v
		}
	} else if len(_opt) == 2 {
		for k := range _context {
			delete(_context, k)
		}
		for k, v := range resp.Context {
			_context[k] = v
		}
		for k := range _status {
			delete(_status, k)
		}
		for k, v := range resp.Status {
			_status[k] = v
		}
	}

	return output, nil
}
